# Generated by Django 2.2.1 on 2020-09-02 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClnProductComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productCode', models.IntegerField(blank=True, max_length=20, null=True)),
                ('userName', models.IntegerField(blank=True, max_length=20, null=True)),
                ('comments', models.IntegerField(blank=True, max_length=2000, null=True)),
                ('commentTime', models.IntegerField(blank=True, max_length=20, null=True)),
                ('sentiments', models.IntegerField(blank=True, max_length=1, null=True)),
                ('commentDate', models.IntegerField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 't_cln_product_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productCode', models.IntegerField(blank=True, max_length=20, null=True)),
                ('userName', models.IntegerField(blank=True, max_length=20, null=True)),
                ('comments', models.IntegerField(blank=True, max_length=2000, null=True)),
                ('commentTime', models.IntegerField(blank=True, max_length=20, null=True)),
                ('commentDate', models.IntegerField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 't_product_comments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(blank=True, max_length=300, null=True)),
                ('productCode', models.IntegerField(blank=True, max_length=20, null=True)),
                ('commentTime', models.IntegerField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 't_product_info',
                'managed': False,
            },
        ),
    ]
